### PR TITLE
Add jemalloc/jeprof profiling

### PR DESCRIPTION
**Pull request by gh2k**
Installs libjemalloc and enables profiling...

For reference, see:
https://medium.com/swlh/native-memory-the-silent-jvm-killer-595913cba8e7
https://github.com/jeffgriffith/native-jvm-leaks/blob/master/README.md
https://technology.blog.gov.uk/2015/12/11/using-jemalloc-to-get-to-the-bottom-of-a-memory-leak/

We should revert this once we've tracked down what we're looking for.

### CODE REVIEW

**Review by JuneKelly — APPROVED** [review]

**Comment by JuneKelly** [comment]
Seems we have a build timeout

**Comment by JuneKelly** [comment]
I've kicked off a re-build, in case it's a bit faster this time, but we may need to up the cloudbuild timeout

**Comment by JuneKelly** [comment]
Nope, still exceeds the timeout

**Comment by JuneKelly** [comment]
@gh2k here's a PR to increase the build timeout: https://github.com/overleaf/google-ops/pull/1708

**Comment by JuneKelly** [comment]
Reading that article, I wonder if we could upgrade apache commons (which contains the delfater / gzip code that we use in `Tar.java`), to https://mvnrepository.com/artifact/org.apache.commons/commons-lang3/3.12.0 . We're currently on 3.7, which is a few years old.

**Comment by gh2k** [comment]
> apache commons

Good shout: https://github.com/overleaf/writelatex-git-bridge/pull/130/files

**Pull request merged**
