### PR TITLE
SLF4J and Better Logging

### PR DESCRIPTION
**Pull request by winstonli**
Swapped out the existing logging with slf4j. All of the logging around main operations has been improved, to help fix issues like #1174. There are also a few small test additions.

### CODE REVIEW

**Comment by winstonli** [comment]
Oops, accidentally closed this when moving it to Done in waffle.io.

**Comment by meis** [comment]
Hi Winston,

I'm looking at this, it seems a great improvement :)

Just two things right now:
- One test is failing:

```
Failed tests: 
  PostbackManagerTest.testRaceWithException:35 Wrong exception was thrown expected same:<uk.ac.ic.wlgitbridge.snapshot.push.exception.InternalErrorException: internal error> was not:<uk.ac.ic.wlgitbridge.snapshot.push.exception.InternalErrorException: internal error>

Tests in error: 
  PostbackManagerTest.testRaceWithVersionId:22 » InternalError internal error
```

 It seems we are trying to compare to instances of errors. Maybe we should compare their classes or something?
- I noticed that there are still a few files using `Util.sout`. Do we have a plan for that?

**Comment by winstonli** [comment]
Great. Those tests should be failing, since they reproduce #1384 (and possibly #1174). The exception instance should be the same. I pushed the fixes in 8cea410, and they should be passing.

With Util.sout, I have just redirected it to use Log.info. We can get rid of it.

**Comment by meis** [comment]
Looks good, Winston. If you can get rid of the last `Util.sout`s in the code we can merge this PR :)

**Comment by winstonli** [comment]
OK, removed Util.souts and .serrs, and changed the logging. Sorry for the delay.

**Pull request merged**
