### PR TITLE
Run GC before swap

### PR DESCRIPTION
**Pull request by JuneKelly**
Closes https://github.com/overleaf/issues/issues/1760

Run GC on a git repo before swapping it to s3.

### CODE REVIEW

**Review by mmazour — APPROVED** [review]
👍 This looks good, though I did become slightly worried about what happens if/when GC fails.

It appears to me the repo will remain on disk (good, since the swap didn't complete), but the logs for errors within `SwapJobImpl.evict` seem to be general-purpose stack traces without a project ID visible in the log. I think that's somewhat bad in general (not just for GC failures). What do you think? Open a ticket for catching errors that can be attributed to a specific project and logging them accordingly, or investigate doing that in the context of this PR?

**Comment by jdleesmiller** [comment]
> but the logs for errors within SwapJobImpl.evict seem to be general-purpose stack traces without a project ID visible in the log

Do you have an example here? I think it's usually been pretty clear from the context, because we only evict one project at a time.

Edit: also, it looks like we'd log it here?
https://github.com/overleaf/writelatex-git-bridge/blob/f849f338dbfabe11fca83b583fa3889e6e48bb12/src/main/java/uk/ac/ic/wlgitbridge/bridge/repo/GitProjectRepo.java#L131

**Comment by mmazour** [comment]
The ones I see in `err.log` look like this:

```
2019-04-13 04:51:17.371 WARN  [Timer-0] GitBridgeApp: Exception while swapping, giving up
java.io.IOException: Too many open files
        at java.io.UnixFileSystem.createFileExclusively(Native Method)
        at java.io.File.createTempFile(File.java:2024)
        at java.io.File.createTempFile(File.java:2070)
        at uk.ac.ic.wlgitbridge.util.Tar$bz2.zip(Tar.java:39)
        at uk.ac.ic.wlgitbridge.bridge.repo.FSGitRepoStore.bzip2Project(FSGitRepoStore.java:139)
        at uk.ac.ic.wlgitbridge.bridge.swap.job.SwapJobImpl.evict(SwapJobImpl.java:165)
        at uk.ac.ic.wlgitbridge.bridge.swap.job.SwapJobImpl.doSwap_(SwapJobImpl.java:122)
        at uk.ac.ic.wlgitbridge.bridge.swap.job.SwapJobImpl.doSwap(SwapJobImpl.java:97)
        at uk.ac.ic.wlgitbridge.util.TimerUtils$1.run(TimerUtils.java:15)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
```

Or like

```
2017-12-17 20:03:10.030 WARN  [Timer-0] GitBridgeApp: Exception thrown during swap job
java.lang.IllegalArgumentException: file too big (2763308763 B): tarTo should have thrown an IOException
        at com.google.api.client.repackaged.com.google.common.base.Preconditions.checkArgument(Preconditions.java:125)
        at uk.ac.ic.wlgitbridge.util.Tar.checkFileSize(Tar.java:113)
        at uk.ac.ic.wlgitbridge.util.Tar.addTarFile(Tar.java:162)
        at uk.ac.ic.wlgitbridge.util.Tar.addTarEntry(Tar.java:128)
        at uk.ac.ic.wlgitbridge.util.Tar.addTarDir(Tar.java:149)
        at uk.ac.ic.wlgitbridge.util.Tar.addTarEntry(Tar.java:126)
        at uk.ac.ic.wlgitbridge.util.Tar.addTarDir(Tar.java:149)
        at uk.ac.ic.wlgitbridge.util.Tar.addTarEntry(Tar.java:126)
        at uk.ac.ic.wlgitbridge.util.Tar.addTarDir(Tar.java:149)
        at uk.ac.ic.wlgitbridge.util.Tar.addTarEntry(Tar.java:126)
        at uk.ac.ic.wlgitbridge.util.Tar.tarTo(Tar.java:80)
        at uk.ac.ic.wlgitbridge.util.Tar$bz2.zip(Tar.java:44)
        at uk.ac.ic.wlgitbridge.bridge.repo.FSGitRepoStore.bzip2Project(FSGitRepoStore.java:80)
        at uk.ac.ic.wlgitbridge.bridge.swap.job.SwapJobImpl.evict(SwapJobImpl.java:165)
        at uk.ac.ic.wlgitbridge.bridge.swap.job.SwapJobImpl.doSwap_(SwapJobImpl.java:122)
        at uk.ac.ic.wlgitbridge.bridge.swap.job.SwapJobImpl.doSwap(SwapJobImpl.java:97)
        at uk.ac.ic.wlgitbridge.util.TimerUtils$1.run(TimerUtils.java:15)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
```

**Comment by jdleesmiller** [comment]
OK, right, I guess I usually look at `out.log`, which has errors and everything else.

It would require some rejigging, but adding the project name in the log line looks not too hard:
https://github.com/overleaf/writelatex-git-bridge/blob/f849f338dbfabe11fca83b583fa3889e6e48bb12/src/main/java/uk/ac/ic/wlgitbridge/bridge/swap/job/SwapJobImpl.java#L124

Could be a follow up task?

**Comment by JuneKelly** [comment]
I've updated that log line to include the project name, re-review please @mmazour ? :)

**Review by mmazour — APPROVED** [review]
LGTM 👍

**Comment by JuneKelly** [comment]
Rebased and squashed :warning:

**Pull request merged**
