### PR TITLE
Empty file in dotgit: direct response to Git Bridge Fails to Clone With IllegalStateException (#3705)

### PR DESCRIPTION
**Pull request by winstonli**
This is directly in response to overleaf/write_latex#3705.

- We test/fix a file size precondition check from `size > 0 && size < Integer.MAX_VALUE` to `size >= 0 && size <= Integer.MAX_VALUE`.

- Also some code quality changes.

It's easiest to go over each commit separately:

1. The code for the failing test
2. The actual fix, which is rather trivial
3. Code to make sure our precondition checks give a bit more info

1 and 3 are the bulk of the changes.

Tested on macOS 10.12.6 and Ubuntu 14.04.5 LTS.

### CODE REVIEW

**Comment by winstonli** [comment]
Added another commit to check the file size on the tar input path too (rather than just the output path). Also stream each file into the tar output stream now, rather than buffer it entirely.

**Review by mmazour — APPROVED** [review]
Thanks very much, Winston.

I can see that this fixes the spurious `file too big` problem. Am I right in thinking it doesn't fix the root cause of the other projects that were marked as evicted but were still on disk?

👍  :shipit:

**Comment by winstonli** [comment]
Thanks for reviewing, Michael! It fixes the root cause because the swapped-and-on-disk projects are due to the tar-bzip decompression partially failing. They fail the first time when encountering an empty file (mis-reporting it as file too big). They fail subsequent times due to the partially-decompressed project already being on disk. I'll write a comment on the issue on how to repair each project.

**Comment by mmazour** [comment]
Great, thanks.

I'd say, OK to go ahead and merge this, and I'll plan to deploy it into production at a low-traffic time - either Friday AM or over the weekend.

**Pull request merged**
